### ISSUE TITLE
tasks due this week should not show the date again since there are headers already

### ISSUE THREAD

**Issue by xeia** [cs2103aug2015-w10-1j/main#102]
change date display for tasks due this week to show time only.

**Comment by whipermr5** [comment]
Be careful for event end dates though; if the event ends on the same date, show just the time, else show the full date

**Comment by whipermr5** [comment]
Actually that same logic can be generalised to all events; can help reduce clutter

**Comment by xeia** [comment]
aight, see the latest commit 'even friendlier date format displays'

**Comment by whipermr5** [comment]
End dates of events that start this week but end after this week aren't correctly shown (should show full date in this case, not just the day). Also, events happening on another year aren't friendly.
