### ISSUE TITLE
Better handling of file write errors

### ISSUE THREAD

**Issue by madsonic** [cs2103aug2015-w10-1j/main#114]
when file is replaced with a folder of same name or change of permission to the file. 
Possible resolution: prompt user to use another path or allow user to overwrite the existing file or folder

**Comment by whipermr5** [comment]
This isn't a bug hahaha I was showing it as a feature. Anyway it's definitely not safe to overwrite a directory as it might contain files. Think just prompting the user to use another path is good enough

**Comment by whipermr5** [comment]
(It's because the exceptions are handled correctly and FileHandler is returning false that we can display the nice error dialog instead of crashing)
