### ISSUE TITLE
separate directory and filename for setpath

### ISSUE THREAD

**Issue by madsonic** [cs2103aug2015-w10-1j/main#97]
set <dir> <file without extension>

**Comment by whipermr5** [comment]
I think let them set the extension too?

**Comment by madsonic** [comment]
i thought you said it wouldn't be that good for user to set extension?

**Comment by madsonic** [comment]
#98. can close this issue after conclusion of file extension discussion

**Comment by whipermr5** [comment]
I think let them customise everything
